apiVersion: v1
kind: Secret
metadata:
  name: jdp-lifecycle-notification-service-kafka-sasl-jaas-config-secret
type: Opaque
data:
  saslJaasConfig: {{ b64enc .Values.global.kafka.saslJaasConfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jdp-lifecycle-notification-service-oauth-secret
type: Opaque
data:
  dctSecret: {{ .Values.global.oauth.dctSecret | b64enc }}
  jwtKey: {{ .Values.global.oauth.jwtKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jdp-lifecycle-notification-service-elasticsearch-secret
type: Opaque
data:
  elasticPassword: {{ .Values.global.elasticsearch.password | b64enc }}

  