apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "lifecycle-notification-service-metrics"
spec:
  selector:
    matchLabels:
      app: {{ template "lifecyclenotificationservice.name" . }}
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
  endpoints:
    - port: "http"
      path: /actuator/prometheus # You may also use a different endpoint, but we suggest to use /prometheus
      interval: 30s
      scrapeTimeout: 5s